
spring:
  datasource:
    url: "jdbc:sqlserver://localhost:1433;databaseName=clinic_booking;encrypt=true;trustServerCertificate=true"
    username: sa
    password: 271125pq
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    Lapplication:
      name=kham-benh

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect